=== ArtemmKozlovv/Training/third task/resources/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/medicines"
        xmlns:tns="http://www.example.org/medicines" elementFormDefault="qualified">
    <element name="medicines">
        <complexType>
            <sequence>
                <element name="medicine" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string" />
                            <element name="pharm" type="string" />
                            <element name="group" >
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="ANTIBIOTICS" />
                                        <enumeration value="PAINKILLERS" />
                                        <enumeration value="ANATI_INFLAMMATORY" />
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="analogs">
                                <complexType>
                                    <sequence>
                                        <element name="analogFirst" minOccurs="0"/>
                                        <element name="analogSecond" minOccurs="0"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="versions" type="long" />
                            <element name="certificate">
                                <complexType>
                                    <sequence>
                                        <element name="number" type="long"/>
                                        <element name="date_of_manufacture" type="string"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="package">
                                <complexType>
                                    <sequence>
                                        <element name="number_of_tablets" type="int"/>
                                        <element name="cost" type="long"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="dosage" type="string" />
                        </sequence>
                        <attribute name="id" type="ID" use="required" />
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== ArtemmKozlovv/Training/third task/resources/medicines-new.xml
<?xml version="1.0" encoding="UTF-8"?><medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/medicines" xsi:schemaLocation="http://www.example.org/medicines medicines.xsd"><medicine id="m2"><name><![CDATA[Xarelto]]></name><pharm>Bayer</pharm><group>ANTIBIOTICS</group><analogs><analogFirst>Kleksan</analogFirst><analogSecond></analogSecond></analogs><versions>1</versions><certificate><number>151</number><date_of_manufacture>2020-06-06</date_of_manufacture></certificate><package><number_of_tablets>28</number_of_tablets><cost>45</cost></package><dosage>1 time per day</dosage></medicine><medicine id="m3"><name><![CDATA[Citramon]]></name><pharm>ООО "Авексима Сибирь"</pharm><group>ANATI_INFLAMMATORY</group><analogs><analogFirst></analogFirst><analogSecond></analogSecond></analogs><versions>3</versions><certificate><number>1392</number><date_of_manufacture>2020-02-02</date_of_manufacture></certificate><package><number_of_tablets>20</number_of_tablets><cost>44</cost></package><dosage>2-3 times a day</dosage></medicine><medicine id="m1"><name><![CDATA[Nurofen]]></name><pharm>Reckitt Benckiser</pharm><group>PAINKILLERS</group><analogs><analogFirst>Ibuklin</analogFirst><analogSecond>Brufen</analogSecond></analogs><versions>2</versions><certificate><number>312</number><date_of_manufacture>2019-12-06</date_of_manufacture></certificate><package><number_of_tablets>20</number_of_tablets><cost>12</cost></package><dosage>3-4 times a day</dosage></medicine></medicines>
